import { CreateDatabaseCommand, CreateTableCommand, DeleteDatabaseCommand, DeleteTableCommand, GetDatabaseCommand, GetTableCommand, GlueClient } from "@aws-sdk/client-glue";
import { client as defaultClient } from "../client.js";
import { GlueError } from "../errors.js";
const fail=(op:string,e:unknown):never=>{throw new GlueError(e instanceof Error&&e.name?e.name:"UNKNOWN",`Glue ${op} failed`,e);};
export async function createDatabase(name:string,glue:GlueClient=defaultClient){try{await glue.send(new CreateDatabaseCommand({DatabaseInput:{Name:name}}));}catch(e){if(e instanceof Error&&e.name==="AlreadyExistsException")return; fail("createDatabase",e);}}
export async function getDatabase(name:string,glue:GlueClient=defaultClient){try{return (await glue.send(new GetDatabaseCommand({Name:name}))).Database;}catch(e){fail("getDatabase",e);}}
export async function createParquetTable(databaseName:string,tableName:string,location:string,glue:GlueClient=defaultClient){try{await glue.send(new CreateTableCommand({DatabaseName:databaseName,TableInput:{Name:tableName,TableType:"EXTERNAL_TABLE",Parameters:{classification:"parquet"},StorageDescriptor:{Location:location,InputFormat:"org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat",OutputFormat:"org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat",Columns:[{Name:"id",Type:"string"}]}}}));}catch(e){if(e instanceof Error&&e.name==="AlreadyExistsException")return; fail("createParquetTable",e);}}
export async function getTable(databaseName:string,tableName:string,glue:GlueClient=defaultClient){try{return (await glue.send(new GetTableCommand({DatabaseName:databaseName,Name:tableName}))).Table;}catch(e){fail("getTable",e);}}
export async function deleteTable(databaseName:string,tableName:string|undefined,glue:GlueClient=defaultClient){if(!tableName)return; try{await glue.send(new DeleteTableCommand({DatabaseName:databaseName,Name:tableName}));}catch(e){if(e instanceof Error&&e.name==="EntityNotFoundException")return; fail("deleteTable",e);}}
export async function deleteDatabase(name:string|undefined,glue:GlueClient=defaultClient){if(!name)return; try{await glue.send(new DeleteDatabaseCommand({Name:name}));}catch(e){if(e instanceof Error&&e.name==="EntityNotFoundException")return; fail("deleteDatabase",e);}}
export const s3TableLocation=(bucket:string,prefix:string)=>`s3://${bucket}/${prefix.replace(/^\/+/,"")}`;
