import { CreateStreamCommand, DeleteStreamCommand, DescribeStreamSummaryCommand, GetRecordsCommand, GetShardIteratorCommand, KinesisClient, PutRecordCommand, PutRecordsCommand } from "@aws-sdk/client-kinesis";
import { client as defaultClient } from "../client.js";
import { KinesisDataStreamsError } from "../errors.js";
const fail=(op:string,e:unknown):never=>{throw new KinesisDataStreamsError(e instanceof Error&&e.name?e.name:"UNKNOWN",`Kinesis ${op} failed`,e);};
export async function createStream(name:string,shards=1,kinesis:KinesisClient=defaultClient){try{await kinesis.send(new CreateStreamCommand({StreamName:name,ShardCount:shards}));}catch(e){if(e instanceof Error&&e.name==="ResourceInUseException")return; fail("createStream",e);}}
export async function describeStream(name:string,kinesis:KinesisClient=defaultClient){try{return (await kinesis.send(new DescribeStreamSummaryCommand({StreamName:name}))).StreamDescriptionSummary;}catch(e){fail("describeStream",e);}}
export async function putJsonRecord(streamName:string,partitionKey:string,data:unknown,kinesis:KinesisClient=defaultClient){try{return (await kinesis.send(new PutRecordCommand({StreamName:streamName,PartitionKey:partitionKey,Data:new TextEncoder().encode(JSON.stringify(data))}))).SequenceNumber;}catch(e){fail("putJsonRecord",e);}}
export async function putJsonRecords(streamName:string,records:{partitionKey:string;data:unknown}[],kinesis:KinesisClient=defaultClient){try{return await kinesis.send(new PutRecordsCommand({StreamName:streamName,Records:records.map(r=>({PartitionKey:r.partitionKey,Data:new TextEncoder().encode(JSON.stringify(r.data))}))}));}catch(e){fail("putJsonRecords",e);}}
export async function getRecords(streamName:string,shardId="shardId-000000000000",kinesis:KinesisClient=defaultClient){try{const it=(await kinesis.send(new GetShardIteratorCommand({StreamName:streamName,ShardId:shardId,ShardIteratorType:"TRIM_HORIZON"}))).ShardIterator; return it?(await kinesis.send(new GetRecordsCommand({ShardIterator:it}))).Records??[]:[];}catch(e){fail("getRecords",e);}}
export async function deleteStream(name:string|undefined,kinesis:KinesisClient=defaultClient){if(!name)return; try{await kinesis.send(new DeleteStreamCommand({StreamName:name,EnforceConsumerDeletion:true}));}catch(e){if(e instanceof Error&&e.name==="ResourceNotFoundException")return; fail("deleteStream",e);}}
