import { CreateEventBusCommand, DeleteEventBusCommand, DeleteRuleCommand, EventBridgeClient, PutEventsCommand, PutRuleCommand, PutTargetsCommand, RemoveTargetsCommand } from "@aws-sdk/client-eventbridge";
import { client as defaultClient } from "../client.js";
import { EventBridgeError } from "../errors.js";
const fail=(op:string,e:unknown):never=>{throw new EventBridgeError(e instanceof Error&&e.name?e.name:"UNKNOWN",`EventBridge ${op} failed`,e);};
export async function createBus(name:string,eb:EventBridgeClient=defaultClient){try{return (await eb.send(new CreateEventBusCommand({Name:name}))).EventBusArn;}catch(e){if(e instanceof Error&&e.name==="ResourceAlreadyExistsException")return name; fail("createBus",e);}}
export async function putRule(name:string,eventBusName:string,source:string,detailType:string,eb:EventBridgeClient=defaultClient){try{return (await eb.send(new PutRuleCommand({Name:name,EventBusName:eventBusName,EventPattern:JSON.stringify({source:[source],"detail-type":[detailType]})}))).RuleArn;}catch(e){fail("putRule",e);}}
export async function putTarget(rule:string,eventBusName:string,targetArn:string,id="target",eb:EventBridgeClient=defaultClient){try{await eb.send(new PutTargetsCommand({Rule:rule,EventBusName:eventBusName,Targets:[{Id:id,Arn:targetArn}]}));}catch(e){fail("putTarget",e);}}
export async function publishEvent(eventBusName:string,source:string,detailType:string,detail:unknown,eb:EventBridgeClient=defaultClient){try{return (await eb.send(new PutEventsCommand({Entries:[{EventBusName:eventBusName,Source:source,DetailType:detailType,Detail:JSON.stringify(detail)}]}))).Entries?.[0]?.EventId;}catch(e){fail("publishEvent",e);}}
export async function deleteRuleWithTargets(rule:string,eventBusName:string,targetIds:string[]=[],eb:EventBridgeClient=defaultClient){try{if(targetIds.length) await eb.send(new RemoveTargetsCommand({Rule:rule,EventBusName:eventBusName,Ids:targetIds})); await eb.send(new DeleteRuleCommand({Name:rule,EventBusName:eventBusName}));}catch(e){if(e instanceof Error&&e.name==="ResourceNotFoundException")return; fail("deleteRuleWithTargets",e);}}
export async function deleteBus(name:string|undefined,eb:EventBridgeClient=defaultClient){if(!name)return; try{await eb.send(new DeleteEventBusCommand({Name:name}));}catch(e){if(e instanceof Error&&e.name==="ResourceNotFoundException")return; fail("deleteBus",e);}}
export const eventPattern=(source:string,detailType:string)=>({source:[source],"detail-type":[detailType]});
