import { CreateDeliveryStreamCommand, DeleteDeliveryStreamCommand, DescribeDeliveryStreamCommand, FirehoseClient, PutRecordBatchCommand, PutRecordCommand } from "@aws-sdk/client-firehose";
import { client as defaultClient } from "../client.js";
import { FirehoseError } from "../errors.js";
const fail=(op:string,e:unknown):never=>{throw new FirehoseError(e instanceof Error&&e.name?e.name:"UNKNOWN",`Firehose ${op} failed`,e);};
export async function createS3DeliveryStream(name:string,bucketArn="arn:aws:s3:::floci-firehose-lab",roleArn="arn:aws:iam::000000000000:role/firehose",fh:FirehoseClient=defaultClient){try{await fh.send(new CreateDeliveryStreamCommand({DeliveryStreamName:name,DeliveryStreamType:"DirectPut",S3DestinationConfiguration:{BucketARN:bucketArn,RoleARN:roleArn}}));}catch(e){if(e instanceof Error&&e.name==="ResourceInUseException")return; fail("createS3DeliveryStream",e);}}
export async function describeDeliveryStream(name:string,fh:FirehoseClient=defaultClient){try{return (await fh.send(new DescribeDeliveryStreamCommand({DeliveryStreamName:name}))).DeliveryStreamDescription;}catch(e){fail("describeDeliveryStream",e);}}
export async function putJsonRecord(name:string,data:unknown,fh:FirehoseClient=defaultClient){try{return (await fh.send(new PutRecordCommand({DeliveryStreamName:name,Record:{Data:new TextEncoder().encode(JSON.stringify(data)+"\n")}}))).RecordId;}catch(e){fail("putJsonRecord",e);}}
export async function putJsonBatch(name:string,records:unknown[],fh:FirehoseClient=defaultClient){try{return await fh.send(new PutRecordBatchCommand({DeliveryStreamName:name,Records:records.map(r=>({Data:new TextEncoder().encode(JSON.stringify(r)+"\n")}))}));}catch(e){fail("putJsonBatch",e);}}
export async function deleteDeliveryStream(name:string|undefined,fh:FirehoseClient=defaultClient){if(!name)return; try{await fh.send(new DeleteDeliveryStreamCommand({DeliveryStreamName:name,AllowForceDelete:true}));}catch(e){if(e instanceof Error&&e.name==="ResourceNotFoundException")return; fail("deleteDeliveryStream",e);}}
